### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jcalvarezjr**
Added Clarify to the Open Company directory

### CODE REVIEW

**Comment by nobodxbodon** [comment]
Looks great. Glad to meet you.

**Comment by waldyrious** [comment]
Hey @nobodxbodon, just a small suggestion: in this case, I'd have either asked @jcalvarezjr to change the commit message to something more specific, or done it myself. That way the git history (and blame views, etc.) can be navigated in a meaningful manner. That said, thanks for handling this one :)

**Comment by nobodxbodon** [comment]
@waldyrious thanks for the suggestion. It makes total sense. I'll keep that in mind.

**Comment by nobodxbodon** [comment]
Hi @jcalvarezjr , seems Clarify site is offline. I wonder if the business is in hibernation?

**Comment by jcalvarezjr** [comment]
Hey @nobodxbodon correct, we can remove Clarify from this list.

**Comment by nobodxbodon** [comment]
We can also move it to another table with archived links as discussed [here](https://github.com/opencompany/awesome-open-company/issues/65), plus any other info you'd like to share.

**Pull request merged**
