### PR TITLE
Fix typo: Mics -> Misc

### PR DESCRIPTION
**Pull request by hkdobrev**
Misc is short for miscellaneous.

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks! Great attention to detail 👍 

While we're at it, what do you think about using a clearer term altogether? The term was introduced by @nobodxbodon in #27. I wonder if he explicitly chose to use different patterns for different companies -- cf. Gratipay/Counchbase ("All products"), Dreamwidth/GitLab ("Dreamwidth"/"GitLab"), and Dangerous Prototypes ("Projects"), for example.

Would it make more sense to use the same terms uniformly, say "All products" and "Various products" (implying that some of their products are not open source)? Or should we simply replace the "Misc" ones with the clearer "Various products" phrasing, ignoring the other outliers mentioned above?

**Comment by hkdobrev** [comment]
I would just choose 1-2 awesome products to list there as per:
- https://github.com/sindresorhus/awesome/blob/master/awesome.md#only-awesome-is-awesome
- https://github.com/sindresorhus/awesome/blob/master/awesome.md#comment-on-why-something-is-awesome

However, a further change like that is more suitable for a separate PR as there could be more feedback and review comments than for a typo :)

**Comment by waldyrious** [comment]
Indeed. And about replacing the "Misc" entries? That feels reasonable in scope to me. (I could make the change if you prefer, just looking to hear your thoughts.)

**Comment by waldyrious** [comment]
I'll take it from your silence that you'd prefer me to do it, which is fine :) I'll merge and make the changes myself. Thanks again for the contribution!

**Comment by hkdobrev** [comment]
Hey, sorry! Just I'm not really sure how to change and this has been sitting in my quite full inbox.

**Comment by waldyrious** [comment]
Don't worry, I understand. I have quite a bit of those in my own backburner ;)

**Pull request merged**
