### PR TITLE
Add SoftwareMill

### PR DESCRIPTION
**Pull request by mmatloka**

### CODE REVIEW

**Comment by mmatloka** [comment]
Hi, I've removed the "Transparency is our priority", website is under reconstruction and there is no clear link for that currently. When we'll get this organized I'll re-add that maybe.

**Comment by waldyrious** [comment]
Thanks, that looks good :+1:

**Comment by mmatloka** [comment]
thank you! :)

**Comment by waldyrious** [comment]
(re-merged the PR to preserve the branching structure; I had mistakenly used the "rebase and merge" option earlier)

**Pull request merged**
