### PR TITLE
Add open properties, and make company list a table (fixes #25)

### LINKED ISSUE #25: specify the aspects of openness
In the list of open companies, it's not obvious whether/how they are more than just based on OSS. For example, Buffer has metrics here: https://buffer.baremetrics.com/dashboard. Do you think it's worthwhile to create some dimensions like 'Open finance' now, and maybe 'Open Operation' in the future, with corresponding links? The list will become a table.

### PR DESCRIPTION
**Pull request by nobodxbodon**
I added the properties as discussed in the issue, without any additional links yet.

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for kicking it off! Would you like to keep this PR open to start filling the table? I feel like it's kind of pointless to make the change without adding at least some of the additional information it supports.

Also, there are two minor fixes needed: re-add spaces between the icons and the corresponding titles, and remove the parenthesis around the statement links (perhaps the quote marks too, if you think that makes sense).

**Comment by nobodxbodon** [comment]
Sure. Could you rank the properties so that I may start with the highest priority ones?

**Comment by waldyrious** [comment]
Phew, that's kinda hard :) Perhaps @whit537 will have better insight. From my POV, I'd rank "open product" highest, followed by (in order of implementation ease) open standards, open communication, and open finance. The latter tree are IMO reversed in terms of actual impact for openness, but I list them like that because I see openness as a multi-staged route where each step is harder (i.e. has more cultural resistance) but is supported by the previous ones. Let me know if you agree -- this is just one guy's opinion :)

**Comment by nobodxbodon** [comment]
I agree with most of your opinion. The open communication and finance are hard to compare IMO, as the operation details can be as sensitive as finance. Maybe I should clarify the meaning of open communication first. As open product in most cases already includes open discussion about development (public bug/issue tracker), I assume open communication is more about the decision making processes about tech/human/finance resources.

**Comment by waldyrious** [comment]
Well, I would define "open product" to mean only open source/open hardware/open specs or equivalent.

For open communication, I'd consider an IRC channel, a public issue tracker (even if there's a private one for sensitive issues or something like that) where developers engage with users in the public one), etc. as valid for those purposes. E.g. UserVoice portals, or even blogs or twitter accounts can be considered open communication channels if there really is some meaningful (i.e. consequential from the POV of the product) interaction between those employed by the company and their "prosumers".

Open decision-making is likely even harder than open finance, since it requires non only transparency, but relinquishing control to some degree. We probably should split that concept from open communication channels, which would make these both concepts better defined and easier to assess.

**Comment by nobodxbodon** [comment]
Indeed. Even if the decision-making can be just read-only to public, it'll inevitably cause feedback which will be hard to ignore completely. 
I'll start with the open product then.

**Comment by nobodxbodon** [comment]
Please check again. I filled in open product & finance columns.
A related question, is it realistic to list all the companies that open source their product/community version? It'll be a long list IMO. Like https://github.com/odoo/odoo, https://github.com/sugarcrm?

**Comment by waldyrious** [comment]
Will review tomorrow. Sorry for the delay :/

**Comment by waldyrious** [comment]
@nobodxbodon, it looks great! This table approach clearly helps define "open company" in a more concrete way, and make our coverage of those aspects more visible. One think I'm unsure of is  Let me know if you'd like to 

Regarding your question:
> is it realistic to list all the companies that open source their product/community version?

No, it's neither realistic nor the expectation. Quoting the [guidelines for inclusion](https://github.com/opencompany/awesome-open-company/wiki/Inclusion%20guidelines) document:
> There's currently only one explicit requirement for adding a new company to the list, which is having a page on their website describing their **commitment to openness and transparency as a core element of the company's operation** (rather than as an additional practice parallel to their main business model).

Following from that, by the way, I'm wondering if we should have the "openness" link in a separate column, and leave the first column to have just the name and main URL of each company. What do you think?

**Comment by nobodxbodon** [comment]
@waldyrious, do we need to merge the "openness" link with current "statement" column then?

About the explicit requirement, I wonder how we can track/collect those companies that meet it? Or do we need to rely on those companies to find this project and contribute to it?

**Comment by waldyrious** [comment]
> @waldyrious, do we need to merge the "openness" link with current "statement" column then?

@nobodxbodon I wouldn't say so, because the former is a static page and (to quote the inclusion guidelines) "easily reachable -- either present in the main navigation menu, or otherwise reachable within 1-2 clicks from the home page", while the latter is typically a blog post or at least written more in the style of an opinion piece, retrospective, or somesuch.

> About the explicit requirement, I wonder how we can track/collect those companies that meet it? Or do we need to rely on those companies to find this project and contribute to it?

Not sure I'm getting what you're asking here -- could you clarify?

**Comment by nobodxbodon** [comment]
After a second thought, I'm not sure it's necessary to add 'Openness' column. As the "only one explicit requirement" is the page with commitment description, it makes sense that the first column is its link, instead of the company homepage. Besides, if the column is named as 'Openness', it sounds like an overall property, instead of the individual properties like the other columns (open product, open finance, etc).

**Comment by waldyrious** [comment]
That's more compact, sure, but I think it would be nice to have a "company" column with the name and the homepage link, and then the relevant openness properties to the right. Also because the inclusion guidelines are not set in stone, so it isn't a given that the openness page will always be the single required openness property.

(In fact, I'd like to hear your thoughts about whether having that one as the single requirement makes sense, or whether we should include something else now that we are defining the remaining properties more explicitly.)

**Comment by nobodxbodon** [comment]
It seems to me the requirement is mostly subjective at the moment. IMO instead of deciding a standard at this moment, it is more important to cover all the aspects of openness, so that it will be clearer which aspects are distinguishable and essential. 

The page of describing commitment to openness seems to me proper to be an aspect named "claiming" or "self statement", rather than general term as "openness", which would make it sounds like *the* criteria to be included in the list.

About the issue of how to track/collect the open companies, I meant the scalability and maintainability of this project. Obviously we can't monitor every new company and check if they meet the requirements. Even keeping track of the companies on the list can be quite some workload. So how can we keep the list up-to-date?

**Comment by waldyrious** [comment]
> The page of describing commitment to openness seems to me proper to be an aspect named "claiming" or "self statement", rather than general term as "openness", which would make it sounds like the criteria to be included in the list.

Agreed. What about "openness pledge"?

> About the issue of how to track/collect the open companies, I meant the scalability and maintainability of this project. Obviously we can't monitor every new company and check if they meet the requirements. Even keeping track of the companies on the list can be quite some workload. So how can we keep the list up-to-date?

I'm quite comfortable with the project being a community-curated list, in the sense that the maintainers ought to try to keep it up to date to the best of their knowledge, but aren't expected to actively go out seeking new entries to add (though they can certainly do so if they wish!). It's a model similar to Wikipedia, where people who come across the list and are interested in the topic will likely know of other companies that could be added, so as long as we keep a welcoming and responsive stance towards contributions, it's likely that the project will remain active and as up-to-date as those interested in it want it to. Does that make sense to you?

**Comment by nobodxbodon** [comment]
> Agreed. What about "openness pledge"?

Sounds good. I'll add the column and put the company homepage in the first column. Some have the pledge on the homepage so they'll be the same link.

>I'm quite comfortable with the project being a community-curated list, in the sense that the maintainers ought to try to keep it up to date to the best of their knowledge, but aren't expected to actively go out seeking new entries to add (though they can certainly do so if they wish!). It's a model similar to Wikipedia, where people who come across the list and are interested in the topic will likely know of other companies that could be added, so as long as we keep a welcoming and responsive stance towards contributions, it's likely that the project will remain active and as up-to-date as those interested in it want it to. Does that make sense to you?

The up-to-dateness would rely on the page visits then. Is this page referenced in other popular pages, like the pages related with open business in Wikipedia? Also, are all the companies notified about their presence in the list? They may be happy to find the other companies with the same values.

**Comment by waldyrious** [comment]
> I'll add the column and put the company homepage in the first column. Some have the pledge on the homepage so they'll be the same link.

Cool 👍 

> The up-to-dateness would rely on the page visits then.

Kind of. It will depend on the popularity of both the project and of the companies. It's a model similar to Wikipedia's: more popular pages get more visits and therefore more vandalism, but also more eyes ensuring they are correct and up to date. One could say this kind of system balances out naturally: if nobody's bothered about the absence of open company X on the list (or correctness/completeness of its entry), it's likely a sign that the company isn't that impactful, so readers of the list won't be too harmed by its lack of proper coverage.

> Is this page referenced in other popular pages, like the pages related with open business in Wikipedia?

Not sure; I believe Wikipedia doesn't reference it, but we could probably add the link to the relevant pages, which shouldn't be a problem since there's no commercial interest and the criterion for inclusion are objective and community-determined. Once this PR is merged I'll add the link to the relevant articles.

> Also, are all the companies notified about their presence in the list? They may be happy to find the other companies with the same values.

The original opencompany.org system relied on active participation of the listed companies, but that is potentially cumbersome if some of them don't have eyes/hands available to comply with the pledge requirements (that's what prompted me to start this list -- see opencompany/www.opencompany.org#103 and opencompany/www.opencompany.org#130 for background). So the goal is to be independent of the companies' involvement, but we can certainly reach out to them :)

**Comment by nobodxbodon** [comment]
Please check the new commit. Would you please open a new issue to keep track of adding the link relevant wiki pages?

**Comment by waldyrious** [comment]
Looks good :) a few observations:

- I don't think we should be using bold this much. Perhaps we could reserve it for the first column, or don't use bold at all
- The "link" in the second column could perhaps be changed to the title of the page
- I would change the 404 error for Neocities to "(archive)" and link to the [archived version](http://wayback.archive.org/web/20150907143713id_/https://neocities.org/stats) for the time being (I think the page may not be down for long -- google has a [cached version from 27 May](https://webcache.googleusercontent.com/search?q=cache:pmirSGSeiIcJ:https://neocities.org/stats%23!+&cd=1&hl=en&ct=clnk&gl=pt))

As for your question, I'm a bit confused by what you mean by "link relevant wiki pages". Can you clarify?

**Comment by nobodxbodon** [comment]
Your three points addressed. PTAL. 
Sorry about the confusion. I meant adding the link *to* the relevant wiki pages, as you mentioned previously.

**Comment by waldyrious** [comment]
Oh, you meant the wikipedia page! I thought you were referring to this repo's wiki, hence my confusion :) sure, I'll create an issue to track that.

**Comment by waldyrious** [comment]
@nobodxbodon sorry for the delay. I've looked into the latest changes and I believe the table is in a state worth merging. Further improvements can be made later, including filling in more cells. Please confirm if you're ok with me merging this.

Furthermore, I will give you access to the repository (let me know if you'd like to join the OpenCompany org as well), so you can make quick fixes without delay. For larger changes, PRs are still preferred.

**Comment by nobodxbodon** [comment]
Sure please go ahead with merging. Thanks for granting me access.
About joining the OpenCompany org, may I ask who are the members?

**Comment by waldyrious** [comment]
I'm not sure what is visible in https://github.com/orgs/opencompany to you -- please take a look and let me know if you have any questions. In any case, org membership is kind of a fluid thing -- it aims to reflect those doing active work in OCI's mission, rather than some sort of sanctioned role.

**Pull request merged**
