### PR TITLE
Add Axem

### PR DESCRIPTION
**Pull request by magyta93**

### CODE REVIEW

**Comment by nobodxbodon** [comment]
Hi, [this page](https://axemsolutions.io/about.html) seems more like 'Openness pledge' to me.

**Comment by magyta93** [comment]
I modified it please check it

**Comment by nobodxbodon** [comment]
Thanks. Merging now.

**Comment by nobodxbodon** [comment]
@magyta93 Nice to meet you. May I ask if you are a member of Axem?

**Pull request merged**
