### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zacnomore**
Broken link

### CODE REVIEW

**Comment by waldyrious** [comment]
Hey @zacnomore, thanks for the PR :)

It appears that neither http://theopencompany.net nor http://theopencompany.org are available at the moment. Maybe we should just remove the entry?

**Comment by zacnomore** [comment]
I was having some pain, maybe I cleaned out my fork? Better PR over here: https://github.com/opencompany/awesome-open-company/pull/57

**Comment by waldyrious** [comment]
I could have done the cleanup myself, I just wanted to check with you if you agreed with my suggestion :)

**Comment by zacnomore** [comment]
I agree. When I made this I checked to find the new page but it's
definitely not there anymore.

**Pull request closed without merging**
