### PR TITLE
Add Countly

### PR DESCRIPTION
**Pull request by gorkem-cetin**
An open source company developing mobile analytics platform.

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the PR! I am not sure this company makes the commitment to openness clear enough apart from releasing the software under an open source license. Neither the about page nor the blog post linked speak directly of openness as a value for the company. So for now I'm inclined to decline this PR, but I'm open to reconsider.

**Comment by waldyrious** [comment]
p.s. do check the [inclusion guidelines](https://github.com/opencompany/awesome-open-company/wiki/Inclusion%20guidelines) for more details on what's expected from entries on this list.

**Comment by gorkem-cetin** [comment]
There is no such a web page, I am afraid. Feel free to close this PR and when there is one, I can reopen. Many thanks, and have a good week!

**Comment by waldyrious** [comment]
Looking forward to that :) Cheers.

**Pull request closed without merging**
