### PR TITLE
Add Watermelon 🍉

### PR DESCRIPTION
**Pull request by baristaGeek**
Add Watermelon

### CODE REVIEW

**Comment by nobodxbodon** [comment]
Hi the open product is labeled as "wemake.services". Typo?

**Comment by baristaGeek** [comment]
Sorry about that @nobodxbodon , I just made the fix

**Comment by nobodxbodon** [comment]
Thanks, merging.
BTW nice idea. It reminds me that in one previous position an auto-analysis would be triggered when submitting a PR to the internal code base, and it may give some warnings to be fixed even before peer review. Feature like this has great potentials to help the reviewing process.

**Comment by baristaGeek** [comment]
> Thanks, merging. BTW nice idea. It reminds me that in one previous position an auto-analysis would be triggered when submitting a PR to the internal code base, and it may give some warnings to be fixed even before peer review. Feature like this has great potentials to help the reviewing process.

Thanks! I'd really appreciate the chance to get your insights on this. It seems like digging into it could provide us with some valuable feedback.

**Pull request merged**
